### ISSUE TITLE
一台电脑同时使用多台手机会出现创建不了session的情况

### ISSUE THREAD

**Issue by trailfight** [electricbubble/guia2#11]
多台手机会出现error，创建不了session，有解决方法吗？
waiting for appium server start, retry times 1
waiting for appium server start, retry times 2
waiting for appium server start, retry times 3
waiting for appium server start, retry times 4
waiting for appium server start, retry times 5
waiting for appium server start, retry times 6
waiting for appium server start, retry times 7
waiting for appium server start, retry times 8
waiting for appium server start, retry times 9
waiting for appium server start, retry times 10

**Comment by electricbubble** [comment]
麻烦提供详细的复现场景，

同时，这个报错提示，在 [appium/appium-uiautomator2-server](https://github.com/appium/appium-uiautomator2-server) 里无法搜索到，确定操作步骤正确吗？

> https://github.com/appium/appium-uiautomator2-server/search?q=waiting+for+appium+server+start&type=code

**Comment by trailfight** [comment]
你好，这个报错提示是在本项目里的， driver.go@v0.1.3第72行
mac连接了两台手机，通过DeviceList()拿到两台手机；然后调用两次NewUSBDriver，分别传入两台device，进行初始化driver的时候，会调用NewSession函数，然后创建session一直失败，输出waiting for appium server start, retry times (1~10).
只连接一台手机的时候是可以正常创建session，初始化driver的。
请问是端口的问题吗，appium默认是6790端口，两台手机都起appium的时候端口冲突了吗，还是什么原因呢

**Comment by electricbubble** [comment]
1. 本项目不会返回这样的报错, 如果 `NewSession` 创建失败, 得到的报错信息也应该是 [appium/appium-uiautomator2-server](https://github.com/appium/appium-uiautomator2-server) 提供的

2. 和 [appium/appium-uiautomator2-server](https://github.com/appium/appium-uiautomator2-server) 的端口无关

---

麻烦提供整个执行流程, 及相关代码, 报错信息也麻烦贴清楚, 方便排查
