### ISSUE TITLE
连接不上appium吗

### ISSUE THREAD

**Issue by Xuzan9396** [electricbubble/guia2#2]
![image](https://user-images.githubusercontent.com/24741439/91001733-1fbb2100-e5ff-11ea-9b2c-40dbc928081c.png)

兄弟方便加个联系方式吗 我的v : xuzan-popin

**Comment by Xuzan9396** [comment]
unknown error: An unknown server-side error occurred while processing the command. Original error: Either JSONWP or W3C capabilities should be provided

**Comment by Xuzan9396** [comment]
v错误： xuzan-poppin 咨询一下问题， 谢谢大神了

**Comment by electricbubble** [comment]
我这个是跳过了 `Appium` 直接去调用 `appium/appium-uiautomator2-server`
> `Appium` 是通过他的 `appium-XXX-driver` 去调用后面的各个 `XXX-server`


所以，使用这个库的时候，是直接访问的 `appium-uiautomator2-server` 的端口 `6790`
```go
// driver, err := guia2.NewDriver(guia2.NewEmptyCapabilities(), "http://localhost:6790/wd/hub")
driver, err := guia2.NewDriver(nil, "http://192.168.1.28:6790/wd/hub")
```

**Comment by Xuzan9396** [comment]
@electricbubble  
![image](https://user-images.githubusercontent.com/24741439/91006404-dd4c1100-e60b-11ea-83bf-c4c7f2c5c7c0.png)
zh'ge
这两个apk是怎么装的， 必须依赖这两个apk吗？有没有直通车下载地址， 有点没明白了

还一个就是6790端口是怎么开启的，通过adb开启吗

**Comment by electricbubble** [comment]
`apk` 需要通过 [appium/appium-uiautomator2-server](https://github.com/appium/appium-uiautomator2-server#building-project) 进行构建

我刚新建了一个 `repo` 存放 `apk`，可直接下载 https://github.com/electricbubble/appium-uiautomator2-server-apk/releases

**Comment by electricbubble** [comment]
@Xuzan9396 当安装好这两个 `apk` 后, 再通过 `adb` 启动服务
> WeChat 的好友申请了
