### ISSUE TITLE
Hello, author

### ISSUE THREAD

**Issue by cplasfwst** [electricbubble/guia2#3]
Hello, author, I would like to ask whether it can be packaged into APK independently without USB, or compiled into APK, and developed for users to use

**Comment by electricbubble** [comment]
Sorry, this project can't be done.

However, [openatx/atx-agent](https://github.com/openatx/atx-agent) + [openatx/uiautomator2](https://github.com/openatx/uiautomator2) can do what you want

**Comment by cplasfwst** [comment]
非常感谢您的回复，很抱歉我现在才看到，我知道您是中国人，所以我直接中文更方便交流对吗
我想用golang做类似autojs的apk
您发给我这两个项目是否是这样的？
我比较喜欢你做的无障碍，但是我想做出无障碍的apk应用，能否实现？我用英文描述可能不够清晰
我会用golang写安卓的界面，您项目的这些功能  我做出来  能否是生成apk 手机不连数据线，我希望是能自己弄一个云端控制

**Comment by electricbubble** [comment]
首先，我认为不可以完全脱离 `USB` 的原因是需要在 `Android 设备` 上启动 `appium-uiautomator2-server`，
这个步骤在 `guia2` 这个项目中，需要用户自己去通过 `USB` 连接 `Android 设备` (至少一次)，再通过 `adb` 启动。

如果这个操作可以在 `Android 设备` 上独自完成，那我认为你的想法是可行的。

同时，我刚刚做了以下尝试：
1. 使用一个独立的 `App (APK)` 去启动 `appium-uiautomator2-server`
    > `Runtime.getRuntime().exec("am instrument -w ...")`
    > `Runtime.getRuntime().exec("/data/local/tmp/launcher")` (`launcher`: 用 `Golang` 实现的启动命令)
    > 均没能达到这个效果，我对这方面如何去执行。。不太了解。。或许有其他的方式
2. 模仿像 [openatx/atx-agent](https://github.com/openatx/atx-agent) 那样，使用 `Golang` 去启动所必需的 `server`
    > `launcher` 依旧需要通过 `USB` 连接去启动这个程序，似乎也没能完全脱离 `USB`，只是相对启动命令可以精简很多。。

**Comment by cplasfwst** [comment]
非常感谢作者！
我也正在学习这方面的知识，因为我之前接触了一个autojs，也是基于无障碍的开发工具
但是我想用golang进行开发，因为我想向着go语言方向进行各种学习
有没有什么第三方库能进行启动无障碍服务，然后编写逻辑来操作手机，真的很想用golang做这个哈
autojs基本也能实现我想的，但是可控度和自由度并非我所喜欢，可惜，我以为你的这个项目基于无障碍又是golang，那天以为中奖了！可惜，为什么必须要基于usb启动的呀T T！！！！

**Comment by electricbubble** [comment]
因为这个项目的实现依赖 `appium-uiautomator2-server`，然而这个服务并不是基于 `无障碍功能`
> 将 `UIAutomator 2.0` 包装成一个在手机端运行的 `server`，主要还是面向开发者使用

**Comment by cplasfwst** [comment]
appium-uiautomator2-server
这个比无障碍好吗？比无障碍稳定吗

**Comment by electricbubble** [comment]
`无障碍功能` 我大概了解了下，需要 `App开发者` 在开发时满足一定的规范，如果不巧遇到开发不够规范的 `app`，
这时候我就认为 `appium-uiautomator2-server` 提供的 `UIAutomator` 更好用了

**Comment by cplasfwst** [comment]
> `无障碍功能` 我大概了解了下，需要 `App开发者` 在开发时满足一定的规范，如果不巧遇到开发不够规范的 `app`，
> 这时候我就认为 `appium-uiautomator2-server` 提供的 `UIAutomator` 更好用了

你知道无障碍有第三方库的吗？

**Comment by electricbubble** [comment]
我还没仔细关注过这方面的。。
不过之前有在社区看到这个项目 [w296488320/XposedAppium](https://github.com/w296488320/XposedAppium)
我觉得也很有意思，也不需要 `USB` 连接设备
